#!/usr/bin/env python3
"""
Applies exact i18n replacements to pages/projects/[id].vue
"""
import sys
from pathlib import Path

if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8', errors='replace')

PROJ_FILE = Path(__file__).resolve().parent.parent / "pages" / "projects" / "[id].vue"

def main():
    content = PROJ_FILE.read_text(encoding='utf-8')
    orig = content

    replacements = [
        # --- Section 1: Header, Breadcrumbs & Badges ---
        ("Lade Projektdaten...", "{{ $t('projects.lade_projektdaten') }}"),
        ("<span>Dashboard</span>", "<span>{{ $t('common.dashboard') }}</span>"),
        ("<span>{{ folder?.name || 'Ordner' }}</span>", "<span>{{ folder?.name || $t('common.ordner') }}</span>"),
        ("<span>{{ project?.title || 'Projekt' }}</span>", "<span>{{ project?.title || $t('common.projekt') }}</span>"),
        ("<span>{{ project.visibility === 'company' ? 'Unternehmen' : 'Privat' }}</span>", "<span>{{ project.visibility === 'company' ? $t('common.unternehmen') : $t('projects.privat') }}</span>"),
        ("{{ project.status === 'completed' ? '✓ Abgeschlossen' : 'Status: ' + project.status }}", "{{ project.status === 'completed' ? ('✓ ' + $t('projects.abgeschlossen')) : ($t('projects.status') + ' ' + project.status) }}"),
        (':title="`Erfasste Zeit: ${project.tracked_hours || 0} Std. ${project.budget_hours ? `/ Budget: ${project.budget_hours} Std.` : \'\'}`"', ':title="`${$t(\'projects.erfasste_zeit\')}: ${project.tracked_hours || 0} ${$t(\'projects.std\')} ${project.budget_hours ? `/ ${$t(\'projects.budget\')}: ${project.budget_hours} ${$t(\'projects.std\')}` : \'\'}`"'),
        (':title="`Fälligkeitsdatum: ${new Date(project.due_date).toLocaleDateString(\'de-CH\')}`"', ':title="`${$t(\'projects.faelligkeitsdatum\')}: ${new Date(project.due_date).toLocaleDateString(\'de-CH\')}`"'),
        ("<span>Fällig: {{ new Date(project.due_date).toLocaleDateString('de-CH') }}</span>", "<span>{{ $t('projects.faellig') }}: {{ new Date(project.due_date).toLocaleDateString('de-CH') }}</span>"),
        ('class="text-[10px] uppercase font-bold text-rose-600 ml-0.5">(Überfällig)</span>', 'class="text-[10px] uppercase font-bold text-rose-600 ml-0.5">({{ $t(\'projects.ueberfaellig\') }})</span>'),
        ('<span v-if="!isFreeUser">Ordner: <NuxtLink', '<span v-if="!isFreeUser">{{ $t(\'projects.ordner\') }} <NuxtLink'),
        ('title="Stoppuhr stoppen & buchen"', ':title="$t(\'projects.stoppuhr_stoppen_buchen\')"'),
        ('title="Projektjournal Seitenleiste öffnen"', ':title="$t(\'projects.journal_sidebar_title\')"'),
        ('<span class="hidden sm:inline">Journal</span>', '<span class="hidden sm:inline">{{ $t(\'projects.journal\') }}</span>'),
        ('title="Weitere Aktionen"', ':title="$t(\'projects.weitere_aktionen\')"'),
        ('<span class="hidden sm:inline">Mehr</span>', '<span class="hidden sm:inline">{{ $t(\'projects.mehr\') }}</span>'),
        ('<div class="px-3 pt-1.5 pb-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">Ansicht</div>', '<div class="px-3 pt-1.5 pb-1 text-[10px] font-bold uppercase tracking-wider text-slate-400">{{ $t(\'projects.ansicht\') }}</div>'),
        ('<span>Kacheln</span>', '<span>{{ $t(\'projects.kacheln\') }}</span>'),
        ('<span>Liste</span>', '<span>{{ $t(\'projects.liste\') }}</span>'),
        ('<span>Projekt-Stoppuhr starten</span>', '<span>{{ $t(\'projects.projekt_stoppuhr_starten\') }}</span>'),
        ('<span>Aufgaben importieren</span>', '<span>{{ $t(\'projects.aufgaben_importieren\') }}</span>'),
        ('<span>Sprachnotiz</span>', '<span>{{ $t(\'projects.sprachnotiz\') }}</span>'),
        ('<span>Neuer Abschnitt</span>', '<span>{{ $t(\'projects.neuer_abschnitt\') }}</span>'),
        ('<div class="px-3 pt-1 pb-0.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">Export (Enterprise)</div>', '<div class="px-3 pt-1 pb-0.5 text-[10px] font-bold uppercase tracking-wider text-slate-400">{{ $t(\'projects.export_enterprise\') }}</div>'),
        ('<span>Projekt als CSV</span>', '<span>{{ $t(\'projects.projekt_als_csv\') }}</span>'),
        ('<span>Projekt als JSON</span>', '<span>{{ $t(\'projects.projekt_als_json\') }}</span>'),
        ('<span>Aufgabe erfassen</span>', '<span>{{ $t(\'projects.aufgabe_erfassen\') }}</span>'),
        ('<span>Zeiterfassung ({{ projectTimeEntries.length || project.time_entry_count || 0 }})</span>', '<span>{{ $t(\'projects.tab_zeiterfassung\') }} ({{ projectTimeEntries.length || project.time_entry_count || 0 }})</span>'),
        ('<span>Team & Berechtigungen ({{ members.length + 1 }})</span>', '<span>{{ $t(\'projects.tab_team\') }} ({{ members.length + 1 }})</span>'),
        ('<span>Kontakte ({{ projectContacts.length }})</span>', '<span>{{ $t(\'common.kontakte\') }} ({{ projectContacts.length }})</span>'),
        ('<span>Projekt-Einstellungen</span>', '<span>{{ $t(\'projects.tab_einstellungen\') }}</span>'),
        ('<span><strong>Viewer-Modus:</strong> Du besitzt Leserechte für dieses Projekt.</span>', '<span><strong>{{ $t(\'projects.viewermodus\') }}</strong> {{ $t(\'projects.du_besitzt_leserechte_für_dieses_pr\') }}</span>'),
        ('<h3 class="text-base font-bold text-slate-800 mt-2">Noch keine Abschnitte in diesem Projekt</h3>', '<h3 class="text-base font-bold text-slate-800 mt-2">{{ $t(\'projects.noch_keine_abschnitte_in_diesem_pro\') }}</h3>'),
        ('<p class="text-xs text-slate-500 mt-1 mb-5">Erstelle den ersten Abschnitt (z.B. "Geplant", "In Bearbeitung", "Abgeschlossen").</p>', '<p class="text-xs text-slate-500 mt-1 mb-5">{{ $t(\'projects.erstelle_den_ersten_abschnitt_zb_ge\') }}</p>'),
        ('+ Ersten Abschnitt erstellen', '{{ $t(\'projects.ersten_abschnitt_erstellen\') }}'),

        # --- Section 2: Search, Filters & Kanban / Table ---
        ('placeholder="Aufgaben durchsuchen (Titel, Notizen, Tags)..."', ':placeholder="$t(\'projects.search_tasks_placeholder\')"'),
        ('<option value="">Alle Prioritäten</option>', '<option value="">{{ $t(\'projects.alle_prioritaeten\') }}</option>'),
        ('<option value="urgent">🔴 Dringend</option>', '<option value="urgent">{{ $t(\'projects.prio_urgent\') }}</option>'),
        ('<option value="high">🟠 Hoch</option>', '<option value="high">{{ $t(\'projects.prio_high\') }}</option>'),
        ('<option value="medium">🟡 Mittel</option>', '<option value="medium">{{ $t(\'projects.prio_medium\') }}</option>'),
        ('<option value="low">🟢 Niedrig</option>', '<option value="low">{{ $t(\'projects.prio_low\') }}</option>'),
        ('<option value="">Alle Zuständigen</option>', '<option value="">{{ $t(\'projects.alle_zustaendigen\') }}</option>'),
        ('<option value="unassigned">Nicht zugewiesen</option>', '<option value="unassigned">{{ $t(\'projects.nicht_zugewiesen\') }}</option>'),
        ('Filter zurücksetzen\n            </button>', '{{ $t(\'projects.filter_zuruecksetzen\') }}\n            </button>'),
        ('title="Kanban Board"', ':title="$t(\'projects.kanban_board\')"'),
        ('<span class="hidden sm:inline">Board</span>', '<span class="hidden sm:inline">{{ $t(\'projects.board\') }}</span>'),
        ('title="Tabellen-Ansicht"', ':title="$t(\'projects.tabellen_ansicht\')"'),
        ('<span class="hidden sm:inline">Tabelle</span>', '<span class="hidden sm:inline">{{ $t(\'projects.tabelle\') }}</span>'),
        ('title="Abschnitt ziehen, um Spalte zu verschieben"', ':title="$t(\'projects.abschnitt_ziehen_um_spalte_zu_versc\')"'),
        ('title="Aufgabe abhaken / Status ändern"', ':title="$t(\'projects.aufgabe_abhaken_status_ändern\')"'),
        ('title="Zeiterfassung läuft..."', ':title="$t(\'projects.zeiterfassung_laeuft\')"'),
        ('title="Ziehen zum Verschieben"', ':title="$t(\'projects.ziehen_zum_verschieben\')"'),
        (':title="`Erfasst: ${task.tracked_hours || 0} Std. ${task.budget_hours ? `/ Budget: ${task.budget_hours} Std.` : \'\'}`"', ':title="`${$t(\'projects.erfasst\')}: ${task.tracked_hours || 0} ${$t(\'projects.std\')} ${task.budget_hours ? `/ ${$t(\'projects.budget\')}: ${task.budget_hours} ${$t(\'projects.std\')}` : \'\'}`"'),
        ('title="Stoppuhr auf diese Aufgabe starten"', ':title="$t(\'projects.stoppuhr_auf_diese_aufgabe_starten\')"'),
        ('<span class="text-[10px]">Start</span>', '<span class="text-[10px]">{{ $t(\'projects.start\') }}</span>'),
        ('<span class="text-cyan-600 font-bold group-hover:translate-x-0.5 transition-transform">Details →</span>', '<span class="text-cyan-600 font-bold group-hover:translate-x-0.5 transition-transform">{{ $t(\'projects.details\') }}</span>'),
        ('Noch keine Aufgaben\n              </div>', '{{ $t(\'projects.noch_keine_aufgaben\') }}\n              </div>'),
        ('+ Aufgabe hinzufügen\n            </button>', '{{ $t(\'projects.aufgabe_hinzufügen\') }}\n            </button>'),
        ('+ Aufgabe erfassen\n              </button>', '{{ $t(\'projects.aufgabe_erfassen_1\') }}\n              </button>'),
        ('Keine Aufgaben gefunden.\n            </div>', '{{ $t(\'projects.keine_aufgaben_gefunden\') }}\n            </div>'),
        ('<th class="py-2.5 px-4">Titel & Beschreibung</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.titel_beschreibung\') }}</th>'),
        ('<th class="py-2.5 px-4">Status</th>', '<th class="py-2.5 px-4">{{ $t(\'common.status\') }}</th>'),
        ('<th class="py-2.5 px-4">Aufwand & Budget</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.aufwand_budget\') }}</th>'),
        ('<th class="py-2.5 px-4">Fälligkeit</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.fälligkeit\') }}</th>'),
        ('<th class="py-2.5 px-4">Felder</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.felder\') }}</th>'),
        ('<th class="py-2.5 px-4 text-right">Aktion</th>', '<th class="py-2.5 px-4 text-right">{{ $t(\'common.aktionen\') }}</th>'),
        ('<span class="font-bold text-slate-900">⏱️ {{ task.tracked_hours || 0 }} Std.</span>', '<span class="font-bold text-slate-900">⏱️ {{ task.tracked_hours || 0 }} {{ $t(\'projects.std\') }}</span>'),
        ('<span v-if="task.budget_hours" class="text-[10px] text-slate-500 font-medium">/ {{ task.budget_hours }} Std.</span>', '<span v-if="task.budget_hours" class="text-[10px] text-slate-500 font-medium">/ {{ task.budget_hours }} {{ $t(\'projects.std\') }}</span>'),
        ('title="Stoppuhr anhalten & Zeit buchen"', ':title="$t(\'projects.stoppuhr_anhalten_zeit_buchen\')"'),
        ('⏹️ Stoppen\n                        </button>', '{{ $t(\'projects.stoppen\') }}\n                        </button>'),
        ('<span class="text-xs text-cyan-700 font-bold hover:underline">Öffnen →</span>', '<span class="text-xs text-cyan-700 font-bold hover:underline">{{ $t(\'projects.öffnen\') }}</span>'),

        # --- Section 8: Task Modal & Task Drawer ---
        ("{{ isEditingTask ? 'Aufgabe bearbeiten' : 'Neue Aufgabe erfassen' }}", "{{ isEditingTask ? $t('projects.aufgabe_bearbeiten') : $t('projects.neue_aufgabe_erfassen') }}"),
        ("Viewer Read-Only\n          </span>", "{{ $t('projects.viewer_readonly') }}\n          </span>"),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Aufgabentitel</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.aufgabentitel\') }}</label>'),
        ('placeholder="z.B. Konzeptentwurf finalisieren"', ':placeholder="$t(\'projects.aufgabentitel_placeholder\')"'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Beschreibung</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.beschreibung\') }}</label>'),
        ('placeholder="Detaillierte Aufgabenbeschreibung, Anforderungen oder Zwischenziele..."', ':placeholder="$t(\'projects.beschreibung_placeholder\')"'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Status</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'common.status\') }}</label>'),
        ('<option value="todo">Zu erledigen (Todo)</option>', '<option value="todo">{{ $t(\'projects.status_todo\') }}</option>'),
        ('<option value="in_progress">In Arbeit (In Progress)</option>', '<option value="in_progress">{{ $t(\'projects.status_in_progress\') }}</option>'),
        ('<option value="review">In Prüfung (Review)</option>', '<option value="review">{{ $t(\'projects.status_review\') }}</option>'),
        ('<option value="done">Abgeschlossen (Done)</option>', '<option value="done">{{ $t(\'projects.status_done\') }}</option>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Fälligkeitsdatum</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.faelligkeitsdatum\') }}</label>'),
        ('Zusatzfelder\n            </h4>', '{{ $t(\'projects.zusatzfelder\') }}\n            </h4>'),
        ('<option value="">-- Nicht ausgewählt --</option>', '<option value="">{{ $t(\'projects.nicht_ausgewaehlt\') }}</option>'),
        ('placeholder="Längeren Text / Notizen eingeben..."', ':placeholder="$t(\'projects.laengeren_text_eingeben\')"'),
        ('Neu\n                </span>', '{{ $t(\'projects.neu\') }}\n                </span>'),
        ('placeholder="Aufgabentitel eingeben..."', ':placeholder="$t(\'projects.aufgabentitel_inline_placeholder\')"'),
        ('title="Bisher erfasster Gesamtaufwand auf dieser Aufgabe"', ':title="$t(\'projects.gesamtaufwand_title\')"'),
        ('<span>{{ drawerTask.tracked_hours || 0 }} Std.</span>', '<span>{{ drawerTask.tracked_hours || 0 }} {{ $t(\'projects.std\') }}</span>'),
        ('title="Stoppen & Buchen"', ':title="$t(\'projects.stoppen_und_buchen\')"'),
        ('<span>Stopp</span>\n                  </button>', '<span>{{ $t(\'projects.stopp\') }}</span>\n                  </button>'),
        ('title="Timer verwerfen"', ':title="$t(\'projects.timer_verwerfen\')"'),
        ('title="Stoppuhr auf diese Aufgabe umschalten"', ':title="$t(\'projects.timer_umschalten_title\')"'),
        ('<span class="hidden sm:inline">Hierher wechseln</span>', '<span class="hidden sm:inline">{{ $t(\'projects.hierher_wechseln\') }}</span>'),
        ('<span class="sm:hidden">Wechseln</span>', '<span class="sm:hidden">{{ $t(\'projects.wechseln\') }}</span>'),
        ('title="Stoppuhr für diese Aufgabe starten"', ':title="$t(\'projects.stoppuhr_starten_title\')"'),
        ('<span>Start</span>\n                </button>', '<span>{{ $t(\'projects.start\') }}</span>\n                </button>'),
        ('title="Schliessen"', ':title="$t(\'projects.schliessen\')"'),
        ('<span>Zusatzfelder</span>\n              </div>', '<span>{{ $t(\'projects.zusatzfelder\') }}</span>\n              </div>'),
        ('<option value="">-- Keine Auswahl --</option>', '<option value="">{{ $t(\'projects.keine_auswahl\') }}</option>'),
        ('placeholder="Details, Notizen oder Beschreibung..."', ':placeholder="$t(\'projects.details_notizen_placeholder\')"'),
        ('<span>Beschreibung</span>\n              </label>', '<span>{{ $t(\'projects.beschreibung\') }}</span>\n              </label>'),
        ('<span>Checkliste & Unteraufgaben</span>', '<span>{{ $t(\'projects.checkliste_unteraufgaben\') }}</span>'),
        ('}} erledigt\n                </span>', '}} {{ $t(\'projects.erledigt_count\') }}\n                </span>'),
        ('Keine Checklisten-Punkte oder Unteraufgaben vorhanden.\n                </div>', '{{ $t(\'projects.keine_checklisten_punkte\') }}\n                </div>'),
        ('title="Hauptpunkt löschen"', ':title="$t(\'projects.hauptpunkt_loeschen\')"'),
        ('title="Unterpunkt löschen"', ':title="$t(\'projects.unterpunkt_loeschen\')"'),
        ('placeholder="+ Unterpunkt zur Checkliste hinzufügen..."', ':placeholder="$t(\'projects.unterpunkt_placeholder\')"'),
        ('+ Unterpunkt\n                      </button>', '{{ $t(\'projects.unterpunkt_btn\') }}\n                      </button>'),
        ('placeholder="+ Neuer Haupt-Checklistenpunkt..."', ':placeholder="$t(\'projects.hauptpunkt_placeholder\')"'),
        ('+ Hauptpunkt\n                </button>', '{{ $t(\'projects.hauptpunkt_btn\') }}\n                </button>'),
        ('<span class="text-xs font-black text-slate-800 uppercase tracking-wider">Zeiterfassung & Budget</span>', '<span class="text-xs font-black text-slate-800 uppercase tracking-wider">{{ $t(\'projects.zeiterfassung_budget\') }}</span>'),
        ('{{ drawerTask.tracked_hours || 0 }} Std.', '{{ drawerTask.tracked_hours || 0 }} {{ $t(\'projects.std\') }}'),
        ('<span>{{ showDrawerTimeMenu ? \'Menü verbergen\' : \'Budget & Manuell buchen\' }}</span>', '<span>{{ showDrawerTimeMenu ? $t(\'projects.menu_verbergen\') : $t(\'projects.budget_manuell_buchen\') }}</span>'),
        ('<label class="block text-[11px] font-bold text-slate-700 mb-1">Aufgaben-Budget (Stunden)</label>', '<label class="block text-[11px] font-bold text-slate-700 mb-1">{{ $t(\'projects.aufgaben_budget_stunden\') }}</label>'),
        ('<label class="block text-[11px] font-bold text-slate-700 mb-1">Aufgaben-Budget (Betrag in {{ project?.currency || \'CHF\' }})</label>', '<label class="block text-[11px] font-bold text-slate-700 mb-1">{{ $t(\'projects.aufgaben_budget_betrag\', { currency: project?.currency || \'CHF\' }) }}</label>'),
        ('<span>Manuell Zeit auf diese Aufgabe buchen</span>', '<span>{{ $t(\'projects.manuell_zeit_buchen\') }}</span>'),
        ('<span class="text-[10px] text-slate-400 font-normal">Wird mit * markiert</span>', '<span class="text-[10px] text-slate-400 font-normal">{{ $t(\'projects.wird_mit_stern_markiert\') }}</span>'),
        ('<label class="block text-[10px] font-bold text-slate-500 mb-0.5">Dauer (Std.)</label>', '<label class="block text-[10px] font-bold text-slate-500 mb-0.5">{{ $t(\'projects.dauer_std\') }}</label>'),
        ('<label class="block text-[10px] font-bold text-slate-500 mb-0.5">Datum</label>', '<label class="block text-[10px] font-bold text-slate-500 mb-0.5">{{ $t(\'projects.datum\') }}</label>'),
        ('<label class="block text-[10px] font-bold text-slate-500 mb-0.5">Stundensatz ({{ project?.currency || \'CHF\' }})</label>', '<label class="block text-[10px] font-bold text-slate-500 mb-0.5">{{ $t(\'projects.stundensatz\') }} ({{ project?.currency || \'CHF\' }})</label>'),
        ('placeholder="Beschreibung / Notiz..."', ':placeholder="$t(\'projects.beschreibung_notiz_placeholder\')"'),
        ('+ Buchen\n                    </button>', '{{ $t(\'projects.buchen_btn\') }}\n                    </button>'),
        ('Ändern\n                      </button>', '{{ $t(\'projects.aendern\') }}\n                      </button>'),
        ('Noch keine Zeiten auf diese Aufgabe gebucht.\n                </div>', '{{ $t(\'projects.noch_keine_zeiten_gebucht\') }}\n                </div>'),
        ('<span>Kommentare & Besprechungsnotizen</span>', '<span>{{ $t(\'projects.kommentare_notizen\') }}</span>'),
        ('Noch keine Kommentare oder Notizen vorhanden.\n                </div>', '{{ $t(\'projects.noch_keine_kommentare\') }}\n                </div>'),
        ('placeholder="Kommentar schreiben... (Strg+Enter zum Senden)"', ':placeholder="$t(\'projects.kommentar_placeholder\')"'),
        ('<span class="text-[10px] text-slate-500 font-medium hidden sm:inline">Tipp: Mit Strg+Enter absenden</span>', '<span class="text-[10px] text-slate-500 font-medium hidden sm:inline">{{ $t(\'projects.tipp_strg_enter\') }}</span>'),
        ('Senden\n                    </button>', '{{ $t(\'projects.senden\') }}\n                    </button>'),
        ('<span>Dateianhänge</span>', '<span>{{ $t(\'projects.dateianhaenge\') }}</span>'),
        ('<p class="text-xs font-bold text-slate-700">Dateien hierher ziehen oder klicken zum Auswählen</p>', '<p class="text-xs font-bold text-slate-700">{{ $t(\'projects.dateien_hierher_ziehen\') }}</p>'),
        ('<p class="text-[10px] text-slate-500 mt-1">Max. 10 MB pro Datei · Bilder, PDFs, Office-Dokumente</p>', '<p class="text-[10px] text-slate-500 mt-1">{{ $t(\'projects.max_file_size_desc\') }}</p>'),
        ('Noch keine Dateien angehängt.\n                </div>', '{{ $t(\'projects.noch_keine_dateien\') }}\n                </div>'),
        ('<span v-if="doc.uploaded_by_name" class="text-cyan-700">· von {{ doc.uploaded_by_name }}</span>', '<span v-if="doc.uploaded_by_name" class="text-cyan-700">· {{ $t(\'projects.von_user\') }} {{ doc.uploaded_by_name }}</span>'),
        ('title="Herunterladen"', ':title="$t(\'projects.herunterladen\')"'),
        ('title="Löschen"', ':title="$t(\'projects.loeschen\')"'),
        ('<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">Abschnitt</label>', '<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">{{ $t(\'projects.abschnitt\') }}</label>'),
        ('<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">Status</label>', '<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">{{ $t(\'common.status\') }}</label>'),
        ('<option value="todo">📋 Zu erledigen (Todo)</option>', '<option value="todo">{{ $t(\'projects.status_todo_icon\') }}</option>'),
        ('<option value="in_progress">🔄 In Arbeit (In Progress)</option>', '<option value="in_progress">{{ $t(\'projects.status_in_progress_icon\') }}</option>'),
        ('<option value="review">🔍 In Prüfung (Review)</option>', '<option value="review">{{ $t(\'projects.status_review_icon\') }}</option>'),
        ('<option value="done">✅ Abgeschlossen (Done)</option>', '<option value="done">{{ $t(\'projects.status_done_icon\') }}</option>'),
        ('<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">Priorität</label>', '<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">{{ $t(\'projects.prioritaet\') }}</label>'),
        ('<option value="niedrig">🟢 Niedrig</option>', '<option value="niedrig">{{ $t(\'projects.prio_low\') }}</option>'),
        ('<option value="normal">🔵 Normal</option>', '<option value="normal">{{ $t(\'projects.prio_normal\') }}</option>'),
        ('<option value="hoch">🟠 Hoch</option>', '<option value="hoch">{{ $t(\'projects.prio_high\') }}</option>'),
        ('<option value="dringend">🔴 Dringend</option>', '<option value="dringend">{{ $t(\'projects.prio_urgent\') }}</option>'),
        ('👥 Zuweisung ({{ drawerTaskAssignedUsers.length }})\n                </label>', '{{ $t(\'projects.zuweisung_label\') }} ({{ drawerTaskAssignedUsers.length }})\n                </label>'),
        ('<span class="text-[10px] text-slate-400 font-semibold">Mehrfachauswahl möglich</span>', '<span class="text-[10px] text-slate-400 font-semibold">{{ $t(\'projects.mehrfachauswahl_moeglich\') }}</span>'),
        ('<span>+ Mitglied zuweisen / ändern...</span>', '<span>{{ $t(\'projects.mitglied_zuweisen_aendern\') }}</span>'),
        ('<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">📅 Fälligkeitsdatum</label>', '<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">{{ $t(\'projects.faelligkeitsdatum_label\') }}</label>'),
        ('<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-2">🎨 Farbmarkierung</label>', '<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-2">{{ $t(\'projects.farbmarkierung_label\') }}</label>'),
        ('Entfernen\n                </button>', '{{ $t(\'projects.farbe_entfernen\') }}\n                </button>'),
        ('<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">🏷️ Tags</label>', '<label class="block text-[11px] font-black text-slate-600 uppercase tracking-wider mb-1.5">{{ $t(\'projects.tags_label\') }}</label>'),
        ('Keine Tags</span>', '{{ $t(\'projects.keine_tags\') }}</span>'),
        ('placeholder="Tag + Enter..."', ':placeholder="$t(\'projects.tag_input_placeholder\')"'),
        ('<span>Aufgabe löschen</span>\n              </button>', '<span>{{ $t(\'projects.aufgabe_loeschen_btn\') }}</span>\n              </button>'),
        ("<span>{{ isCreatingTaskInDrawer ? 'Aufgabe wird beim Speichern/Schliessen angelegt' : 'Änderungen werden automatisch gespeichert' }}</span>", "<span>{{ isCreatingTaskInDrawer ? $t('projects.drawer_create_notice') : $t('projects.drawer_autosave_notice') }}</span>"),
        ('Aufgabe erstellen\n            </button>', '{{ $t(\'projects.aufgabe_erstellen_btn\') }}\n            </button>'),
        ('Schliessen\n            </button>', '{{ $t(\'projects.schliessen\') }}\n            </button>'),

        # --- Section 7: Section Management Modal ---
        ('Neuen Abschnitt anlegen\n        </h3>', '{{ $t(\'projects.abschnitt_anlegen_title\') }}\n        </h3>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Titel des Abschnitts</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.abschnitt_titel_label\') }}</label>'),
        ('placeholder="z.B. Vorbereitung, In Bearbeitung oder Abnahme"', ':placeholder="$t(\'projects.abschnitt_titel_placeholder\')"'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Sichtbarkeits-Modus</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.sichtbarkeits_modus\') }}</label>'),
        ('<option value="standard">Standard (Alle Projektmitglieder haben Zugriff)</option>', '<option value="standard">{{ $t(\'projects.sichtbarkeit_standard\') }}</option>'),
        ('<option value="custom">Eingeschränkt (Nur Owner & explizit berechtigte Personen)</option>', '<option value="custom">{{ $t(\'projects.sichtbarkeit_eingeschraenkt\') }}</option>'),
        ('Projekt-Abschnitte verwalten\n          </h3>', '{{ $t(\'projects.abschnitte_verwalten_title\') }}\n          </h3>'),
        ('placeholder="Abschnittsbezeichnung"', ':placeholder="$t(\'projects.abschnittsbezeichnung\')"'),
        ('title="Farbe zurücksetzen"', ':title="$t(\'projects.farbe_zuruecksetzen\')"'),
        ('title="Nach oben verschieben"', ':title="$t(\'projects.nach_oben\')"'),
        ('title="Nach unten verschieben"', ':title="$t(\'projects.nach_unten\')"'),
        ('title="Abschnitt löschen"', ':title="$t(\'projects.abschnitt_loeschen_title\')"'),
        ('placeholder="+ Weiterer Abschnitt (z.B. Zwischenprüfung, Abnahme)..."', ':placeholder="$t(\'projects.weiterer_abschnitt_placeholder\')"'),

        # --- Section 9: Excel/CSV Import Modal ---
        ('<h3 class="text-lg font-black text-slate-900">Aufgaben aus Excel / CSV importieren</h3>', '<h3 class="text-lg font-black text-slate-900">{{ $t(\'projects.import_modal_title\') }}</h3>'),
        ('<p class="text-xs text-slate-500 mt-0.5">\n              Lade eine CSV- oder Tabellendatei hoch und weise die Spalten flexibel den Feldern in Taskster zu.\n            </p>', '<p class="text-xs text-slate-500 mt-0.5">\n              {{ $t(\'projects.import_modal_desc\') }}\n            </p>'),
        ('<p class="text-sm font-bold text-slate-800">Excel- (.xlsx, .xls) oder CSV-Datei auswählen oder hierher ziehen</p>', '<p class="text-sm font-bold text-slate-800">{{ $t(\'projects.import_drag_drop_title\') }}</p>'),
        ('<p class="text-xs text-slate-500 mt-1">Unterstützt Formate: Excel (.xlsx, .xls) sowie CSV, TSV (Trennzeichen: Komma, Semikolon, Tab)</p>', '<p class="text-xs text-slate-500 mt-1">{{ $t(\'projects.import_formats_desc\') }}</p>'),
        ('Andere Datei wählen\n            </button>', '{{ $t(\'projects.import_choose_other_file\') }}\n            </button>'),
        ('Ziel-Abschnitt für importierte Aufgaben:\n            </label>', '{{ $t(\'projects.import_target_section\') }}\n            </label>'),
        ('Spaltenzuweisung (Mapping):\n              </label>', '{{ $t(\'projects.import_mapping_title\') }}\n              </label>'),
        ('<span class="text-[11px] text-slate-500 font-medium">Titel-Spalte ist Pflichtfeld</span>', '<span class="text-[11px] text-slate-500 font-medium">{{ $t(\'projects.import_title_mandatory\') }}</span>'),
        ('+ Eigenes Feld anlegen\n                </button>', '{{ $t(\'projects.import_create_custom_field\') }}\n                </button>'),
        ('<th class="py-2.5 px-4">Spalte in Datei</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.import_col_in_file\') }}</th>'),
        ('<th class="py-2.5 px-4">Beispielwert (Zeile 1)</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.import_example_value\') }}</th>'),
        ('<th class="py-2.5 px-4">Wird zugewiesen an Feld</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.import_mapped_to\') }}</th>'),
        ('<option value="">-- Ignorieren --</option>', '<option value="">{{ $t(\'projects.import_ignore\') }}</option>'),
        ('<optgroup label="Standard-Felder">', '<optgroup :label="$t(\'projects.import_standard_fields\')">'),
        ('<option value="title">📌 Aufgabentitel (Pflicht)</option>', '<option value="title">{{ $t(\'projects.import_field_title\') }}</option>'),
        ('<option value="description">📋 Beschreibung</option>', '<option value="description">{{ $t(\'projects.import_field_desc\') }}</option>'),
        ('<option value="status">Status (todo/in_progress/done)</option>', '<option value="status">{{ $t(\'projects.import_field_status\') }}</option>'),
        ('<option value="due_date">📅 Fälligkeitsdatum</option>', '<option value="due_date">{{ $t(\'projects.import_field_due\') }}</option>'),
        ('<option value="priority">Priorität (niedrig/normal/hoch/dringend)</option>', '<option value="priority">{{ $t(\'projects.import_field_priority\') }}</option>'),
        ('<option value="tags">🏷️ Tags</option>', '<option value="tags">{{ $t(\'projects.import_field_tags\') }}</option>'),
        ('<optgroup v-if="fields.length > 0" label="Bestehende Zusatzfelder">', '<optgroup v-if="fields.length > 0" :label="$t(\'projects.import_existing_custom_fields\')">'),
        ('<optgroup label="✨ Als neues Zusatzfeld anlegen">', '<optgroup :label="$t(\'projects.import_create_as_new_field\')">'),
        ('<optgroup label="📋 Vorlagen-Zusatzfelder" v-if="getAvailableTemplateFields(header).length > 0">', '<optgroup :label="$t(\'projects.import_template_custom_fields\')" v-if="getAvailableTemplateFields(header).length > 0">'),
        ('Vorschau der ersten Zeilen:\n            </label>', '{{ $t(\'projects.import_preview_rows\') }}\n            </label>'),
        ('<h4 class="text-lg font-black text-slate-900">Import erfolgreich abgeschlossen!</h4>', '<h4 class="text-lg font-black text-slate-900">{{ $t(\'projects.import_success_title\') }}</h4>'),
        ('<p class="text-xs text-slate-600">\n            Es wurden <strong>{{ importSuccessCount }}</strong> Aufgaben erfolgreich in den Abschnitt eingepflegt.\n          </p>', '<p class="text-xs text-slate-600">\n            {{ $t(\'projects.import_success_desc\', { count: importSuccessCount }) }}\n          </p>'),
        ("<span>{{ importingTasks ? 'Importiere...' : 'Import starten (' + importParsedRows.length + ' Aufgaben)' }}</span>", "<span>{{ importingTasks ? $t('projects.import_running') : $t('projects.import_start_btn', { count: importParsedRows.length }) }}</span>"),

        # --- Section 4 & 5: Custom Fields & Logic Modal ---
        ("<span v-if=\"isStandardFieldModal\">⚡ Logik-Regel: {{ newFieldLabel }}</span>\n          <span v-else>{{ editingFieldId ? 'Feld bearbeiten' : 'Neues benutzerdefiniertes Feld' }}</span>", "<span v-if=\"isStandardFieldModal\">{{ $t('projects.cf_modal_rule_title', { label: newFieldLabel }) }}</span>\n          <span v-else>{{ editingFieldId ? $t('projects.cf_modal_edit_field') : $t('projects.cf_modal_new_field') }}</span>"),
        ("<span v-if=\"isStandardFieldModal\">Bestimme, unter welcher Bedingung dieses Standard-Feld sichtbar ist.</span>\n          <span v-else>Definiere ein Attribut f&#252;r Aufgaben oder das Projekt.</span>", "<span v-if=\"isStandardFieldModal\">{{ $t('projects.cf_modal_rule_desc') }}</span>\n          <span v-else>{{ $t('projects.cf_modal_new_desc') }}</span>"),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Gültigkeitsbereich</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.cf_gueltigkeitsbereich\') }}</label>'),
        ('Aufgaben-Feld\n              </button>', '{{ $t(\'projects.cf_aufgaben_feld\') }}\n              </button>'),
        ('Projekt-Feld\n              </button>', '{{ $t(\'projects.cf_projekt_feld\') }}\n              </button>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Feld-Bezeichnung (Label)</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.cf_feld_bezeichnung\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Feldtyp</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.cf_feldtyp\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Optionen (Komma-getrennt)</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.cf_optionen_komma\') }}</label>'),
        ('Bedingte Logik (Feld nur unter Bedingung anzeigen)\n              </label>', '{{ $t(\'projects.cf_bedingte_logik\') }}\n              </label>'),
        ('<span class="text-xs font-bold text-slate-700">Bedingung definieren</span>', '<span class="text-xs font-bold text-slate-700">{{ $t(\'projects.cf_bedingung_definieren\') }}</span>'),
        ('Bedingung entfernen\n              </button>', '{{ $t(\'projects.cf_bedingung_entfernen\') }}\n              </button>'),
        ('Abh&#228;ngig von Feld</label>', '{{ $t(\'projects.cf_abhaengig_von_feld\') }}</label>'),
        ('<option value="">-- Feld ausw&#228;hlen --</option>', '<option value="">{{ $t(\'projects.cf_feld_auswaehlen\') }}</option>'),
        ('<optgroup label="Standard-Aufgabenfelder">', '<optgroup :label="$t(\'projects.cf_standard_aufgabenfelder\')">'),
        ('<optgroup label="Eigene Felder"', '<optgroup :label="$t(\'projects.cf_eigene_felder\')"'),
        ('Nur anzeigen wenn Wert gleich:</label>', '{{ $t(\'projects.cf_nur_anzeigen_wenn\') }}</label>'),
        ('<option value="">-- Wert ausw&#228;hlen --</option>', '<option value="">{{ $t(\'projects.cf_wert_auswaehlen\') }}</option>'),
        ('<option value="assigned">Mind. eine Person zugewiesen</option>', '<option value="assigned">{{ $t(\'projects.cf_mind_eine_person\') }}</option>'),
        ('<option value="unassigned">Keine Person zugewiesen</option>', '<option value="unassigned">{{ $t(\'projects.cf_keine_person\') }}</option>'),
        ('<option value="set">Datum ist gesetzt</option>', '<option value="set">{{ $t(\'projects.cf_datum_gesetzt\') }}</option>'),
        ('<option value="not_set">Kein Datum</option>', '<option value="not_set">{{ $t(\'projects.cf_kein_datum\') }}</option>'),
        ('<option value="overdue">&#220;berf&#228;llig</option>', '<option value="overdue">{{ $t(\'projects.ueberfaellig\') }}</option>'),
        ('<option value="today">Heute f&#228;llig</option>', '<option value="today">{{ $t(\'projects.heute_faellig\') }}</option>'),
        ('<option value="set">Farbe gesetzt</option>', '<option value="set">{{ $t(\'projects.cf_farbe_gesetzt\') }}</option>'),
        ('<option value="not_set">Keine Farbe</option>', '<option value="not_set">{{ $t(\'projects.cf_keine_farbe\') }}</option>'),
        ('<option value="set">Mind. ein Tag gesetzt</option>', '<option value="set">{{ $t(\'projects.cf_mind_ein_tag\') }}</option>'),
        ('<option value="not_set">Keine Tags</option>', '<option value="not_set">{{ $t(\'projects.cf_keine_tags\') }}</option>'),
        ("{{ isStandardFieldModal ? 'Regel speichern' : 'Feld speichern' }}", "{{ isStandardFieldModal ? $t('projects.cf_regel_speichern') : $t('projects.cf_feld_speichern') }}"),

        # --- Section 4: General Settings Tab ---
        ('Allgemeine Projekt-Einstellungen\n          </h3>', '{{ $t(\'projects.settings_general_title\') }}\n          </h3>'),
        ('Passe den Projektnamen, den Status und projektweite Eigenschaften an.\n          </p>', '{{ $t(\'projects.settings_general_desc\') }}\n          </p>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Projekttitel</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.projekttitel\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Projekt-Status</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.projekt_status\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Sichtbarkeit des Projekts</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.sichtbarkeit_des_projekts\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Projekt-Währung</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.projekt_waehrung\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Budget (Stunden)</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.budget_stunden\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Budget (Betrag)</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.budget_betrag\') }}</label>'),
        ('Benutzerdefinierte Felder & Logik\n          </h3>', '{{ $t(\'projects.benutzerdefinierte_felder_logik\') }}\n          </h3>'),
        ('Sichtbarkeit Standard-Felder\n            </h4>', '{{ $t(\'projects.sichtbarkeit_standard_felder\') }}\n            </h4>'),
        ('Hier kannst du Standard-Felder unter bestimmten Bedingungen ausblenden.\n            </p>', '{{ $t(\'projects.sichtbarkeit_standard_desc\') }}\n            </p>'),
        ('Immer sichtbar</span>', '{{ $t(\'projects.immer_sichtbar\') }}</span>'),

        # --- Section 5: Zeiterfassung / Controlling Tab ---
        ('Gesamtaufwand</div>', '{{ $t(\'projects.gesamtaufwand\') }}</div>'),
        ('Stunden-Budget</div>', '{{ $t(\'projects.stunden_budget\') }}</div>'),
        ('Gesamtkosten</div>', '{{ $t(\'projects.gesamtkosten\') }}</div>'),
        ('Kosten-Budget</div>', '{{ $t(\'projects.kosten_budget\') }}</div>'),
        ('<option value="all">Alle Buchungen (Projekt & Aufgaben)</option>', '<option value="all">{{ $t(\'projects.alle_buchungen\') }}</option>'),
        ('<option value="project_only">Nur Gesamtprojekt (ohne Aufgabe)</option>', '<option value="project_only">{{ $t(\'projects.nur_gesamtprojekt\') }}</option>'),
        ('<option value="">Alle Mitarbeiter</option>', '<option value="">{{ $t(\'projects.alle_mitarbeiter\') }}</option>'),
        ('<th class="py-2.5 px-4">Rapportiert auf</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.rapportiert_auf\') }}</th>'),
        ('<th class="py-2.5 px-4">Tätigkeit / Notiz</th>', '<th class="py-2.5 px-4">{{ $t(\'projects.taetigkeit_notiz\') }}</th>'),
        ('✏️ Zeiteintrag anpassen\n          </h3>', '{{ $t(\'projects.zeiteintrag_anpassen\') }}\n          </h3>'),
        ('⏱️ Zeit erfassen\n          </h3>', '{{ $t(\'projects.zeit_erfassen\') }}\n          </h3>'),

        # --- Section 6: Team & Contacts Modals ---
        ('Teammitglied ins Projekt einladen\n          </h3>', '{{ $t(\'projects.teammitglied_einladen\') }}\n          </h3>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">E-Mail des Nutzers</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.email_des_nutzers\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Rolle im Projekt</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.rolle_im_projekt\') }}</label>'),
        ('<option value="editor">Editor (Darf Aufgaben erstellen & bearbeiten)</option>', '<option value="editor">{{ $t(\'projects.rolle_editor_desc\') }}</option>'),
        ('<option value="viewer">Viewer (Nur Leserechte)</option>', '<option value="viewer">{{ $t(\'projects.rolle_viewer_desc\') }}</option>'),
        ('Mitglied hinzufügen\n            </button>', '{{ $t(\'projects.mitglied_hinzufuegen_btn\') }}\n            </button>'),
        ('KI-Autofill Assistent\n            </h4>', '{{ $t(\'projects.ki_autofill_assistent\') }}\n            </h4>'),
        ('placeholder="Beispiel: Hans Peter, Bauleiter bei Steiner Tiefbau AG in Zürich, Tel 044 123 45 67, Mobile 079 987 65 43, h.peter@steiner.ch"', ':placeholder="$t(\'projects.ki_autofill_placeholder\')"'),
        ('<span class="text-[11px] text-slate-500 font-medium">Texte werden sicher verarbeitet</span>', '<span class="text-[11px] text-slate-500 font-medium">{{ $t(\'projects.texte_sicher_verarbeitet\') }}</span>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Vorname</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.vorname\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Nachname *</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.nachname\') }} *</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Firma / Unternehmen</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.firma_unternehmen\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Funktion / Gewerk</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.funktion_gewerk\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Mobile (Handy)</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.mobile_handy\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Telefon Festnetz</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.telefon_festnetz\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Geschäftsadresse</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.geschaeftsadresse\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Webseite</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.webseite\') }}</label>'),
        ('<label class="block text-xs font-bold text-slate-700 mb-1">Gruppe / Kategorie</label>', '<label class="block text-xs font-bold text-slate-700 mb-1">{{ $t(\'projects.gruppe_kategorie\') }}</label>'),
        ("{{ isEditingContact ? 'Kontakt speichern' : 'Kontakt anlegen' }}", "{{ isEditingContact ? $t('projects.kontakt_speichern_btn') : $t('projects.kontakt_anlegen_btn') }}"),
    ]

    applied = 0
    for old, new in replacements:
        if old in content:
            content = content.replace(old, new)
            applied += 1

    print(f"Applied {applied} of {len(replacements)} substitutions.")

    if content != orig:
        PROJ_FILE.write_text(content, encoding='utf-8')
        print("[OK] pages/projects/[id].vue template successfully updated!")
    else:
        print("[WARN] No changes made to pages/projects/[id].vue")

if __name__ == '__main__':
    main()
